### PR TITLE
re #34: reproduce in CI

### LINKED ISSUE #34: Warns maybe-uninitialized on g++-6
A quick one:
```shellsession
$ cmake -DCMAKE_CXX_COMPILER=g++-6 ..
```
causes this:
```shellsession
In file included from /opt/jpmag/proj/extern/fast_float/include/fast_float/ascii_number.h:9:0,
                 from /opt/jpmag/proj/extern/fast_float/include/fast_float/parse_number.h:3,
                 from /opt/jpmag/proj/extern/fast_float/include/fast_float/fast_float.h:44,
                 from /opt/jpmag/proj/extern/fast_float/tests/random_string.cpp:1:
/opt/jpmag/proj/extern/fast_float/include/fast_float/float_common.h: In function ‘fast_float::adjusted_mantissa fast_float::parse_long_mantissa(const char*, const char*) [with binary = fast_float::binary_format<double>]’:
/opt/jpmag/proj/extern/fast_float/include/fast_float/float_common.h:134:35: error: ‘answer.fast_float::adjusted_mantissa::mantissa’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     return mantissa == o.mantissa && power2 == o.power2;
            ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from /opt/jpmag/proj/extern/fast_float/include/fast_float/parse_number.h:4:0,
                 from /opt/jpmag/proj/extern/fast_float/include/fast_float/fast_float.h:44,
                 from /opt/jpmag/proj/extern/fast_float/tests/random_string.cpp:1:
/opt/jpmag/proj/extern/fast_float/include/fast_float/decimal_to_binary.h:73:21: note: ‘answer.fast_float::adjusted_mantissa::mantissa’ was declared here
   adjusted_mantissa answer;
                     ^~~~~~
make[1]: *** [CMakeFiles/Makefile2:216: tests/CMakeFiles/long_exhaustive32_64.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by biojppm**
re #34

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. We deliberately want C++ to treat the objects as trivial, hence the default constructor.

I have added inline initializer which should hopefully do away with the warning. Please sync your branch.

**Comment by biojppm** [comment]
@lemire The previous changes do reproduce the problem in the CI.

I [think it is a genuine one](https://github.com/lemire/fast_float/blob/8a0a0c4fc1afeabd65d55302e900aac2594e3bc5/include/fast_float/decimal_to_binary.h#L101): in absence of ctor initialization, this statement will return `mantissa` uninitialized:

image

**Comment by biojppm** [comment]
I see you've added a fix.

**Comment by biojppm** [comment]
It's curious that later gcc versions fail to point to this issue.

**Comment by lemire** [comment]
> It's curious that later gcc versions fail to point to this issue.

I submit to you that it is because it is not an issue.

> I think it is a genuine one: in absence of ctor initialization, this statement will return mantissa uninitialized:

I disagree. Here is the code...

```C++
  adjusted_mantissa am = pns.too_many_digits ? parse_long_mantissa<binary_format<T>>(first,last) : compute_float<binary_format<T>>(pns.exponent, pns.mantissa);
  if(am.power2 < 0) { am = parse_long_mantissa<binary_format<T>>(first,last); }
```

See how if `am.power2` is negative, then mantissa is never used?

It is not needed that mantissa ever be initialized if it is never being read.

If the compiler is not smart enough, its analysis will end up with a false positive.

**Comment by lemire** [comment]
Great PR. Merging.

**Comment by biojppm** [comment]
Thanks for clarifying.

**Pull request merged**
